[workspace]
resolver = "2"
members = [
    "packages/web",
    "packages/api", 
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }
reqwest = {version = "0.12.24"}
tokio = {version = "1.48.0"}

# workspace
api = { path = "packages/api" }
